Automation test: Switching network regression
levelkdev/swapr-dapp pull request #1037
Opened 2022-06-01 05:26 UTC by MilanVojnovic95

# Summary

This is a regression test for switching network, and this scenario has many times caused that application crash (black screen).
All details of the scenario and steps can be found at this [link](https://docs.google.com/spreadsheets/d/129Vr4cxi9z1McOAXHy2gU3RD4xL_IwwU7V9_T0YYxLU/edit#gid=204937697&range=62:62).

  # To Test

- [ ] Run test for SwitchingNetworkTests.ts with yarn synpress:run {path to file}
- [ ] The test should be performed successfully

2022-06-01 11:38 UTC, niemam29 commented on tests/synpress/specs/transactionfull/swap/SwapTests.ts
> -    SwapPage.getTransactionConfirmedModal()
same

2022-06-08 13:33 UTC, denciu reviewed
Looks good, have nothing more to add than what @niemam29 mentioned. Resolve these and I will be happy to approve.

2022-06-08 20:43 UTC, MilanVojnovic95 commented
@niemam29 @denciu 
Fixed required things, please take a look.

2022-06-09 11:25 UTC, denciu requested changes

2022-06-09 11:25 UTC, denciu commented on tests/synpress/specs/transactionfull/swap/SwapTests.ts
> +>>>>>>> automation-tests-ecobridge
Leftovers from resolving conflicts

2022-07-13 09:44 UTC, niemam29 requested changes

2022-07-13 13:18 UTC, MilanVojnovic95 commented on tests/synpress/specs/transactionfull/swap/SwapTests.ts
> +    SwapPage.getTransactionConfirmedModal().should('be.visible').should('contain.text', 'Transaction Submitted')
will be solved 👍

2022-08-31 14:00 UTC, closed without merging