Fix for yarn start on Windows
levelkdev/swapr-dapp pull request #1091
Opened 2022-06-15 07:08 UTC by niemam29

# Summary

Noticed that on Windows there are some problems with starting swapr due to env variables. Fixed that by cross-env-shell

  # To Test

1. Try to run yarn start

2022-06-15 07:13 UTC, wixzi commented
I think this will break in linux and mac environments. Also if your commit message is same try to `amend commit` and  ` force push` so it don't create so many commits

2022-06-15 09:10 UTC, denciu commented
> I think this will break in linux and mac environments. Also if your commit message is same try to `amend commit` and ` force push` so it don't create so many commits

Works on ubuntu

2022-06-15 09:15 UTC, denciu commented
> I think this will break in linux and mac environments. Also if your commit message is same try to `amend commit` and ` force push` so it don't create so many commits

That's true, on ubuntu it generates files under completely different directory. That's also a reason why CI fails. See img:
![image](https://user-images.githubusercontent.com/26334170/173791000-8ea0df0f-47a3-49e8-a04b-aff4fa80ddca.png)

2022-06-16 09:39 UTC, adamazad requested changes

2022-06-16 09:39 UTC, adamazad commented on package.json
> +    "codegen:socket": "cross-env TARGET=src/services/EcoBridge/Socket/api/generated PROPERTIES='typescriptThreePlus=true' yarn codegen:execute",
I would put all this into a bash. :) cc @denciu

2022-06-17 16:40 UTC, wixzi commented
> @wixzi @denciu Fixed problems, now it works both on Windows and Linux, would be good to have it tested on Mac. About the commits, they will be squashed before merge anyway because i'm using "squash and merge" from github, so i'm not sure if that's necessary

Its working in mac as well. 👍🏼

2022-06-22 11:14 UTC, adamazad commented
@niemam29 fix conflicts and merge

2022-07-13 21:51 UTC, wixzi approved these changes

2022-07-26 14:57 UTC, berteotti approved these changes

2022-08-22 08:30 UTC, adamazad commented
@niemam29 is this still an issue?

2022-11-29 11:52 UTC, closed without merging