bugfix: Swapr is looking for a route endlessly when wallet is not connected
levelkdev/swapr-dapp pull request #1104
Opened 2022-06-21 11:12 UTC by adamazad

# Summary

_Fixes_ #1099 as a hotfix.

2022-06-21 17:41 UTC, Diogomartf approved these changes

2022-06-23 10:39 UTC, mix1o approved these changes

2022-06-24 07:25 UTC, niemam29 requested changes
Swapr should estimate output of swap even when wallet is disconnected

2022-06-29 21:18 UTC, wixzi commented
@adamazad can we check and merge this. @0xVenky was checking with me.

2022-06-29 21:20 UTC, adamazad commented
> @adamazad can we check and merge this. @0xVenky was checking with me.

I think it requires a major redesign in the swap state.

2022-07-04 14:53 UTC, niemam29 approved these changes

2022-07-04 14:53 UTC, merged