Fix expiring quotes
levelkdev/swapr-dapp pull request #1259
Opened 2022-07-18 11:07 UTC by jorgedclopes

# Summary

Fixes #1255

Add feature to recompute the trades periodically.
Set frequency to 2 minutes.

  # To Test

Go to 'Swap' page
Select token from XDAI to USDC (for example)
Select 'Cow' exchange option
Click on 'Wrap' button
Confirm wrap on Metamask
Click on 'Swap with CoW'
Click on 'Confirm Swap'
Click on 'Sing' (and you will get error message)

  # Background

COW/Gnosis trades quotes don't come with a TTL. In order to work around this, we will set it on our end.
It doesn't seem to be possible to compute the quote just for the COW trade and cascade that information without computing for all trades. Given that, we periodically compute for all trades.

2022-07-18 12:06 UTC, jorgedclopes commented
Not fixed yet. Back to development.

2022-07-18 12:07 UTC, Diogomartf commented
Still got the error in the preview!

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5664434/179507733-d77c7003-4417-44d4-9aa3-b151a56fe00a.png">

2022-07-18 12:25 UTC, adamazad requested changes

2022-07-18 12:25 UTC, adamazad commented on src/state/swap/hooks.ts
> +    setEndOfTime(currentTime + quoteTTL)
Setting state here causes re-render(s) of this function.

2022-07-18 12:25 UTC, adamazad commented on src/state/swap/hooks.ts
> +  const [computeSwitch, setComputeSwitch] = useState(false)
Use a timeOut ref that is set in `.then` of `getExactIn/Out`

2022-07-18 21:53 UTC, adamazad approved these changes
Works as expected. Just might make sense to think about the UX if anyone @zamli has any suggestions.

2022-07-19 08:41 UTC, niemam29 commented
For me this problem still sometimes occur, esp. when i am waiting a bit before swapping.
![cach2](https://user-images.githubusercontent.com/30408272/179707190-313d2474-b782-420b-af98-dca9ab073676.png)

2022-07-26 13:00 UTC, MilanVojnovic95 approved these changes
Tested several times and everything seems ok. 👍

2022-07-26 14:43 UTC, berteotti approved these changes
LGTM, simple and clear

2022-07-27 21:58 UTC, adamazad commented
This should be merged. The only thing I would like to see is that refreshing the quote should happen silently. The loading animation seems too distracting, at least. @zamli what do you think UX/UI wise?

2022-08-01 12:14 UTC, merged