[Fix] Fix button message when wrapping
levelkdev/swapr-dapp pull request #768
Opened 2022-03-15 11:10 UTC by berteotti

# Summary

Fixes #720

Fix button message when wrapping but there is enough ETH/WETH balance

*Add screenshots if applicable. Images are nice :)*
![Screenshot 2022-03-15 at 11 08 35](https://user-images.githubusercontent.com/23079677/158365082-ff78f9ee-aaab-40a5-a65c-e567ba77e05b.png)

  # To Test

1. Open Swap page
2. Choose to wrap ETH to WETH with enough balance
- [ ] Button message is "Enter ETH amount"
2. Choose to unwrap WETH to ETH with enough balance
- [ ] Button message is "Enter WETH amount"

2022-03-16 16:41 UTC, karczuRF approved these changes

2022-03-16 17:03 UTC, karczuRF requested changes

2022-03-17 09:18 UTC, berteotti commented on public/locales/en.json
> +  "insufficientETHBalance": "Insufficient ETH balance",
Fixed!

2022-03-17 09:18 UTC, berteotti commented on src/hooks/useWrapCallback.ts
> +        inputError: sufficientBalance ? undefined : !typedValue ? t('enterETHAmount') : t('insufficientETHBalance')
Fixed!

2022-03-17 09:44 UTC, karczuRF approved these changes

2022-03-17 09:56 UTC, karczuRF commented
@berteotti LGTM, nice job! Works as expected ;)

Two more things, although it's probably out of scope of this issue. Do we need new tickets for them?
1. When testing I've noticed that for different tokens button doesn't show symbol within the button message (enter X amount), so I feel it's kinda inconsistent from ui perspective. What do you think?
2. After landing page merge some button's colors are buggy, so the color is white instead of dark. But that's what I've noticed also in different pages, eg for Bridge.

![image](https://user-images.githubusercontent.com/88723742/158784126-39ba5dd8-b71c-4197-be9a-3f564ed2c92e.png)

2022-03-17 11:49 UTC, mix1o approved these changes
Good job. Works as expected

2022-03-17 18:37 UTC, karczuRF commented
> @berteotti LGTM, nice job! Works as expected ;)
> 
> Two more things, although it's probably out of scope of this issue. Do we need new tickets for them?
> 
> 1. When testing I've noticed that for different tokens button doesn't show symbol within the button message (enter X amount), so I feel it's kinda inconsistent from ui perspective. What do you think?
> 2. After landing page merge some button's colors are buggy, so the color is white instead of dark. But that's what I've noticed also in different pages, eg for Bridge.
> 

I've created new issue for that (https://github.com/levelkdev/swapr-dapp/issues/783), so this one can be closed.

2022-03-17 22:23 UTC, merged