feature: add Gnosis Protocol v2 trade to the Eco Router
levelkdev/swapr-dapp pull request #781
Opened 2022-03-17 13:08 UTC by adamazad

# Summary

Adds support for GPv2 into the Eco Router. 

1. Support for viewing orders. 
2. Support for signing orders.
3. Orders expire within 30 minutes by default.
4. `GnosisProtocolTrade.getExactTradeIn` and `GnosisProtocolTrade.getExactTradeOut` support receiver parameter, but the UI does not use those. They can be used after #639 is implemented.

## Notes

- Signing messages is not possible with Coinbase Wallet. COW trade should not 
- Original COW UI - CowSwap - does not support canceling orders, but it would be nice to implement it here since `GnosisProtocolTrade.cancelOrder` is implemented in [swapr-sdk#63](https://github.com/levelkdev/swapr-sdk/pull/63)
- GPv2 fees sometimes are sub 1 bps (< 0.01%), so the UI should have a way to show it
- This PR uses a custom build from the SDK located at [SwaprDAO/swapr-sdk-bundle](https://github.com/SwaprDAO/swapr-sdk-bundle). Do NOT merge this PR until [swapr-sdk#63](https://github.com/levelkdev/swapr-sdk/pull/63) is merged and a new official release of the SDK is published. 

# To Test

1. COW in SwapBox
   ![image](https://user-images.githubusercontent.com/1926216/158814088-c37fe996-a42c-4f61-99e5-ad0bac1c811f.png)
2. Swap confirmation modal
    ![image](https://user-images.githubusercontent.com/1926216/158814249-15054246-48a9-4b6d-a44a-b1169594f88d.png)
5. Sign the order via MM
    ![image](https://user-images.githubusercontent.com/1926216/158814302-c3417987-4db9-4086-a254-26024096f085.png)
6. Order history
    ![image](https://user-images.githubusercontent.com/1926216/158814410-59618c4d-ecd4-4b04-bff8-40a468203429.png)
7. Order fullfilment toast notification
   ![image](https://user-images.githubusercontent.com/1926216/158814470-55512fb0-0a4b-451f-b549-5bb06e6dae88.png)

# Background

The PR branch is coming from #616's branch because of the SDK architecture re-design. Once the latter is merged, the comparison table will look less messy.

2022-03-18 11:42 UTC, niemam29 commented
Hey, i've notice that sometimes, when switching tokens there is a "loading" inscription under swap box. Is it on purpose @adamazad?

https://user-images.githubusercontent.com/30408272/158997012-4029ac93-b53b-4b83-a608-0a7021096d90.mp4

2022-03-18 13:32 UTC, Mi-Lan requested changes
Very big pr nice job! Code looks very good, I just left couple of comments. Will do the some testing now!

2022-03-18 13:32 UTC, Mi-Lan commented on src/hooks/useKpiTokens.ts
> +          numerator: parseUnits(
This is good practice makes code more readable, we should be doing this! Especially when there is more parameters.

2022-03-18 13:32 UTC, Mi-Lan commented on src/hooks/useSwapCallback.ts
> +// import isZero from '../utils/isZero'
we can delete this...

2022-03-18 13:32 UTC, Mi-Lan commented on src/hooks/useSwapCallback.ts
> +    console.log(trades)
this console log also

2022-03-18 13:32 UTC, Mi-Lan commented on src/hooks/useSwapsGasEstimate.ts
> +          // const options = !value || isZero(value as string) ? {} : { value }
Is this commented stuff needed?

2022-03-18 13:32 UTC, Mi-Lan commented on src/pages/RemoveLiquidity/index.tsx
> +    const router = getRouterContract(chainId, library, UniswapV2RoutablePlatform.SWAPR, account)
Im just wondering for learning purpose this new UniswapV2RoutablePlatform class from SDK was it made to distinguish between regular amm-s and cowswap/curve?

2022-03-18 13:32 UTC, Mi-Lan commented on src/utils/index.ts
> +  // RoutablePlatform,
this can be deleted too

2022-03-18 13:55 UTC, Mi-Lan commented
> Hey, i've notice that sometimes, when switching tokens there is a "loading" inscription under swap box. Is it on purpose @adamazad?
> 
>  Untitled_.Mar.18.2022.12_40.PM.mp4

Yeah I got this also. Its related to ui getting native token balance and not wrapping before transaction.

2022-03-18 14:35 UTC, Mi-Lan commented
Seems that on this pr when I select certain pairs it only shows cowswap when it should be rest of pairs for example in wxdai/gno
This pr:
![Screenshot 2022-03-18 at 15 31 46](https://user-images.githubusercontent.com/33226956/159022212-f88bdee3-3c6f-4a12-87d2-a11a208e2ea5.png)
Production:
![Screenshot 2022-03-18 at 15 32 07](https://user-images.githubusercontent.com/33226956/159022271-800bd5a4-2341-4f7b-b561-26bc004717fe.png)
This might be related to native/wrapped currency as well
Also I noticed that for a split second it only shows cowswap and then the rest of pairs...

https://user-images.githubusercontent.com/33226956/159022630-38adba2a-abe9-43ba-afc7-b044a422aaf8.mov

2022-03-18 14:43 UTC, Mi-Lan commented
I think it should be checked if swapr pairs show up for certain pairs. Because now even in wxdai/weth when it loads I dont see swapr...In production its there
Production:
![Screenshot 2022-03-18 at 15 43 06](https://user-images.githubusercontent.com/33226956/159024346-c7689526-8a7f-44a6-9e92-6e242255c6c8.png)
This pr:
![Screenshot 2022-03-18 at 15 43 28](https://user-images.githubusercontent.com/33226956/159024441-a72197b1-4048-486d-ad30-96d2e57c5970.png)

2022-03-21 10:19 UTC, berteotti commented on package.json
> +    "ethers": "^5.4.0",
Is this downgrade intended?

2022-03-21 10:22 UTC, berteotti reviewed
Is the [curve-logo.svg](https://github.com/levelkdev/swapr-dapp/pull/781/files#diff-63f08353c456635341c0ca3e7b230c980555fac075e72231d0e7785b40eaa460) necessary in this PR?

2022-03-21 10:23 UTC, berteotti commented on src/components/Popups/TransactionPopup.tsx
> +            View on {isGnosisProtocolHash ? 'Gnosis Protocol Explorer' : 'block explorer'}
Can you add this to translations?

2022-03-21 10:24 UTC, berteotti commented on src/components/TransactionConfirmationModal/index.tsx
> +                View on {isGnosisProtocolTrade ? 'Gnosis Protocol Explorer' : 'block explorer'}
Can you add this line and line 92 to translations?

2022-03-21 10:29 UTC, berteotti commented on src/utils/prices.ts
> +  }
This `if` can be removed.

2022-03-21 10:31 UTC, berteotti commented on src/utils/prices.ts
> +  }
Should we be doing something with `pct` value? Because this `if` does nothing and we can delete this 4 lines.

2022-03-21 10:41 UTC, berteotti commented on src/hooks/useSwapsGasEstimate.ts
> +// import isZero from '../utils/isZero'
We can delete this too

2022-04-11 14:03 UTC, adamazad commented
Closing this to same reasons outlined in #616

2022-04-11 14:03 UTC, closed without merging