Fix showing avatar empty space on accounts with ENS but no image attached
levelkdev/swapr-dapp pull request #865
Opened 2022-04-08 16:10 UTC by Diogomartf

# Summary

Closes #824

This PR fixes showing extra empty space on accounts with ENS without image attached.

**Current**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/5664434/162479957-cdb4f19f-c02e-4550-8c83-9c5d69273328.png">
**Old**
<img width="941" alt="image" src="https://user-images.githubusercontent.com/5664434/162480756-ef2c679c-9a6d-4515-b773-27de98aa6cc1.png">

  # To Test

1. Open swapr app
	  - [ ] Connect to an ETH account with ENS and without avatar attached
	  - [ ] Check there isn't any empty space at the left.

2022-04-11 09:21 UTC, MilanVojnovic95 commented
Tested and looks ok to me 👍

2022-04-11 09:27 UTC, niemam29 commented
Looks good to me!

2022-04-13 08:37 UTC, karczuRF approved these changes

2022-04-14 11:53 UTC, kingalg commented
Looks good to me as well! I have a question - @niemam29 @MilanVojnovic95 - when I'm impersonating a few people in a row for a second or two I can see avatar of previously impersonated person. Looks buggy/laggy. Did you saw something like this?

![Screenshot 2022-04-14 at 13.51.38.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/688524e5-6f41-46c3-88f7-e109333cf808)

2022-04-14 14:02 UTC, Diogomartf commented
> Looks good to me as well! I have a question - @niemam29 @MilanVojnovic95 - when I'm impersonating a few people in a row for a second or two I can see avatar of previously impersonated person. Looks buggy/laggy. Did you saw something like this?
> 
> ![Screenshot 2022-04-14 at 13.51.38.png](https://camo.githubusercontent.com/2a8f2294d660f7ae2d2844cc668565190cd90942402708e43535fb8c04d27e1d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631623861653863343032316235626137663933646266322f36383835323465352d366634312d343663332d383866372d653130393333336366383038)

I didn't test it impersonating a few people. I'll check and see if I can make it less buggy. 

Thanks for testing!

2022-04-18 08:24 UTC, adamazad requested changes
Look good!

2022-04-18 08:24 UTC, adamazad commented on src/components/Web3Status/AccountStatus.tsx
> +
```suggestion
```

2022-04-18 08:33 UTC, adamazad approved these changes

2022-04-18 08:42 UTC, berteotti approved these changes

2022-04-18 08:42 UTC, merged