Feature/eco bridge fixes
levelkdev/swapr-dapp pull request #874
Opened 2022-04-11 11:51 UTC by mix1o

Post review amendments

2022-04-11 12:25 UTC, adamazad requested changes
This is a good start! Few more concerns to address, and we can merge this. :)

2022-04-11 12:25 UTC, adamazad commented on src/services/EcoBridge/EcoBridge.types.ts
> +}
SyncState maybe?

2022-04-11 12:25 UTC, adamazad commented on src/services/EcoBridge/EcoBridgeProvider.tsx
> +export const EcoBridgeProvider: FC = ({ children }: { children?: React.ReactNode }) => {
I think `FC` add `children` property

2022-04-11 12:25 UTC, adamazad commented on src/services/EcoBridge/Socket/SocketBridge.ts
> +import { BigNumber } from 'ethers/lib/ethers'
This import should be either:

```typescript
import { BigNumber } from 'ethers'
```

or 

```typescript
import { BigNumber } from '@ethersproject/bignumber'
```

Pick whichever you like.

2022-04-11 12:25 UTC, adamazad commented on src/services/EcoBridge/Arbitrum/ArbitrumBridge.selectors.ts
> +          summary.status = 'pending' // deposits on l1 should never show confirmed on ui
Can change this to an enum as well?

2022-04-15 03:00 UTC, adamazad approved these changes
Awesome job! Let's merge this!

2022-04-15 08:34 UTC, denciu approved these changes

2022-04-15 08:36 UTC, merged